### ISSUE TITLE
`build_defined_names()` assumes cells exist

### ISSUE THREAD

**Issue by strichter** [bradbase/xlcalculator#4]
I use named ranges for all sorts of templating support and sometimes named range cells do not have values. Just ignore names that do not reference a cell with a value. At best create a warning.

**Comment by bradbase** [comment]
crap.

So better support a_thing=Sheet1!A1 where Sheet1!A1 is an empty cell?

**Comment by strichter** [comment]
Yes, that would probably be best.

**Comment by bradbase** [comment]
There is potential the empty cell might need to be legitimized.

That said, neither of us need that behavior. The immediate fix will be to ignore defined names that refer to empty cells and raise a warning.

Note: Currently there's no mechanism to define a name after the model is created. Potentially a gap in features. Probably best to add the feature if anyone wants it rather than hack build_defined_names to make a decision on behalf of the user.

**Comment by bradbase** [comment]
Please try v0.0.6b

**Comment by bradbase** [comment]
There is potential for the current fix for this issue to have omitted support for the use case where a defined name has a formula for the definition (rather than a cell). #5
